apiVersion: apps/v1
kind: Deployment #Kubernetesresource kind we are creating
metadata:
  name: springboot-k8s-yaml
spec:
  selector:
    matchLabels:
      app: springboot-k8s-yaml
  replicas: 2 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: springboot-k8s-yaml
    spec:
      containers:
        - name: springboot-k8s-yaml
          image: springbootk8sdemo # Image that will be used to containers in the cluster
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080 # The port that the container is running on in the cluster
